---
name: CI

#Controls when the branch will run
on:
  push: 
    branches: [main]
#Triggers the workflow
  pull-request:
    branch: [main]

  workflow_dispatch:

jobs: 
  build:  
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
    # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


 


  



