---
name: CI

#Controls when the branch will run
on:
#Triggers the workflow
  pull-request:
    branch: [main]

jobs: 
  build:  
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

  



