---
name: CI

#Controls when the branch will run
on:
  push: 
    branches:
      - dev-1
#Triggers the workflow
  pull-request:
    branch: [main]

jobs: 
  build:  
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
  
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          ref: develop # Make sure we checkout to the correct branch


  



